# Generated by Django 6.0.3 on 2026-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("event_type", models.CharField(max_length=32)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("max_anomaly_c", models.FloatField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "event_type", "sent_at"],
                        name="api_alertlo_email_bbe069_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("radius_deg", models.FloatField(default=2.0)),
                ("alert_heatwave", models.BooleanField(default=True)),
                ("alert_upwelling", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "latitude", "longitude"),
                        name="unique_alert_subscription",
                    )
                ],
            },
        ),
    ]
